"""edit

Revision ID: 80b0533f7fb5
Revises: e3ea9e30daa1
Create Date: 2024-03-15 01:56:14.136091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b0533f7fb5'
down_revision = 'e3ea9e30daa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('in_stock',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('in_stock',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
